version: "3"
services:
  db:
    container_name: chat-go-server-db
    image: mysql
    volumes:
      - ./docker/mysql/db/mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    command: mysqld

  redis:
    container_name: chat-go-server-redis
    image: "redis:latest"
    volumes:
      - ./docker/redis/db/redis_data:/data
    environment:
      - REDIS_PORT
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server

  api:
    container_name: chat-go-server-api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./:/go/src/github.com/karamaru-alpha/chat-go-server
    ports:
      - "8080:8080"
    environment:
      - PORT
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - REDIS_PORT
    depends_on:
      - db
      - redis
