version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: go mod download
      - run:
          name: Install golangci-lint@v1.39.0
          command: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.39.0
      - run:
          name: Run golangci-lint
          command: ./bin/golangci-lint run
      - run:
          name: Run test
          command: go test ./test/...
