// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package room

import (
	room3 "github.com/karamaru-alpha/chat-go-server/application/room/create"
	room4 "github.com/karamaru-alpha/chat-go-server/application/room/find_all"
	"github.com/karamaru-alpha/chat-go-server/domain/model/room"
	"github.com/karamaru-alpha/chat-go-server/infrastructure/mysql"
	room2 "github.com/karamaru-alpha/chat-go-server/infrastructure/mysql/room"
	room5 "github.com/karamaru-alpha/chat-go-server/interfaces/handler/room"
	"github.com/karamaru-alpha/chat-go-server/interfaces/proto/pb"
	"github.com/karamaru-alpha/chat-go-server/util"
)

// Injectors from wire.go:

// DI dependency injection about room
func DI() chatserver.RoomServicesServer {
	iulidGenerator := util.NewULIDGenerator()
	iFactory := room.NewFactory(iulidGenerator)
	db := mysql.ConnectGorm()
	iRepository := room2.NewRepositoryImpl(db)
	iInputPort := room3.NewInteractor(iFactory, iRepository)
	roomIInputPort := room4.NewInteractor(iRepository)
	roomServicesServer := room5.NewHandler(iInputPort, roomIInputPort)
	return roomServicesServer
}
