DROP TABLE IF EXISTS `rooms`;

CREATE TABLE IF NOT EXISTS `rooms` (
  `id`    CHAR(26)    NOT NULL        COMMENT 'トークルームULID',
  `title` VARCHAR(64) NOT NULL UNIQUE COMMENT 'トークルーム名',
  PRIMARY KEY (`id`))
ENGINE=InnoDB
COMMENT='トークルーム'
DEFAULT CHARSET=utf8mb4;
