CREATE DATABASE IF NOT EXISTS `chat_go_server`;
USE `chat_go_server`;

DROP TABLE IF EXISTS `rooms`;

CREATE TABLE IF NOT EXISTS `rooms` (
  `id`    INT AUTO_INCREMENT NOT NULL COMMENT 'トークルームID',
  `title` VARCHAR(64) NOT NULL UNIQUE COMMENT 'トークルーム名',
  PRIMARY KEY (`id`))
ENGINE=InnoDB
COMMENT='トークルーム'
DEFAULT CHARSET=utf8mb4;
